services:
  postgres:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 512M

  redis:
    deploy:
      resources:
        limits:
          memory: 128M

  backend:
    environment:
      ENVIRONMENT: production
    deploy:
      resources:
        limits:
          memory: 256M
    restart: always

  caddy:
    profiles: []
    restart: always
