#!/usr/bin/env bash
# Copyright (C) 2026 Gerald Hofbauer <info@geraldhofbauer.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GRN='\033[0;32m'; YLW='\033[1;33m'; BLD='\033[1m'; RST='\033[0m'
info()  { echo -e "${GRN}[+]${RST} $*"; }
warn()  { echo -e "${YLW}[!]${RST} $*"; }
error() { echo -e "${RED}[✗]${RST} $*" >&2; exit 1; }
step()  { echo -e "\n${BLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RST}\n${BLD}  $*${RST}\n${BLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RST}"; }
ok()    { echo -e "${GRN}  ✓${RST}  $*"; }

SERVER_PORT="${SERVER_PORT:-8765}"
SERVER_URL="http://localhost:${SERVER_PORT}"
CLI_BIN="./bin/pwmgr"

# ─────────────────────────────────────────────────────────────────────────────
echo
echo -e "${BLD}  Passbubble Setup${RST}"
echo -e "  Self-hosted password manager — first-run initialisation"
echo

# ── Prerequisites ─────────────────────────────────────────────────────────────
step "1/5  Prerequisites"
command -v docker  >/dev/null 2>&1 || error "docker not found"
docker compose version >/dev/null 2>&1 || error "docker compose plugin not found"
command -v go      >/dev/null 2>&1 || error "go not found (need Go 1.22+)"
command -v openssl >/dev/null 2>&1 || error "openssl not found"
ok "docker, go, openssl — all present"

# ── Generate .env ─────────────────────────────────────────────────────────────
step "2/5  Environment (.env)"

if [[ -f .env ]]; then
  warn ".env already exists — keeping existing secrets"
  warn "Delete .env and re-run to generate fresh secrets"
else
  PG_PASS=$(openssl rand -base64 32 | tr -d '/+=\n')
  RD_PASS=$(openssl rand -base64 32 | tr -d '/+=\n')
  JWT=$(openssl rand -base64 64 | tr -d '/+=\n')

  cat > .env <<EOF
# Passbubble — generated by setup.sh on $(date -Iseconds)
# Keep this file secret and out of version control!

POSTGRES_PASSWORD=${PG_PASS}
REDIS_PASSWORD=${RD_PASS}
JWT_SECRET=${JWT}

SERVER_PORT=${SERVER_PORT}
ENVIRONMENT=development
ADMIN_EMAIL=

# Production only (Caddy TLS)
DOMAIN=
CADDY_EMAIL=
EOF
  ok ".env created with cryptographically random secrets"
fi

# ── Build CLI ─────────────────────────────────────────────────────────────────
step "3/5  Build CLI (pwmgr)"

mkdir -p bin
info "Compiling cli/cmd/pwmgr → ${CLI_BIN} ..."
(cd cli && go build -ldflags="-s -w" -o "../${CLI_BIN}" ./cmd/pwmgr) \
  || error "CLI build failed — run: cd cli && go build ./cmd/pwmgr"
ok "Built ${CLI_BIN}"

# ── Start containers ──────────────────────────────────────────────────────────
step "4/5  Start Docker services"

info "docker compose up -d --build  (this may take a few minutes on first run)"
docker compose up -d --build

# ── Wait for backend ──────────────────────────────────────────────────────────
step "5/5  Wait for backend"

MAX_WAIT=180
ELAPSED=0
printf "  Backend starting"
until curl -sf "${SERVER_URL}/health" >/dev/null 2>&1; do
  sleep 3
  ELAPSED=$((ELAPSED + 3))
  printf "."
  if [[ $ELAPSED -ge $MAX_WAIT ]]; then
    echo
    error "Backend did not become healthy after ${MAX_WAIT}s.\nRun: docker compose logs backend"
  fi
done
echo
ok "Backend healthy at ${SERVER_URL}"

# ── Register admin ────────────────────────────────────────────────────────────
echo
echo -e "${BLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RST}"
echo -e "${BLD}  Register your admin account${RST}"
echo -e "${BLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RST}"
echo
echo "  The first account is automatically promoted to admin."
echo "  No invitation token required for this initial setup."
echo
echo "  Web app:    ${SERVER_URL}/web/"
echo "  Admin panel: ${SERVER_URL}/admin/  (requires the admin account below)"
echo

exec "${CLI_BIN}" setup --server "${SERVER_URL}"
