// Cross-language interop test: verifies TypeScript crypto produces identical
// output to the Go implementation (backend/pkg/crypto and cli/internal/crypto).
//
// The test vectors are generated by:
//   cd cli && go run ./cmd/gen-test-vectors -out ../packages/shared-ts/testdata/vectors.json
//
// vectors.json is committed so tests run without the Go toolchain.

import { readFile } from 'fs/promises';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { describe, expect, it, beforeAll } from 'vitest';
import { aesGcmDecrypt, aesGcmEncrypt } from '../aes-gcm.js';
import { deriveKey } from '../argon2.js';
import { decryptDataKey, encryptDataKey } from '../hybrid-kem.js';
import { x25519SharedSecret } from '../x25519.js';
import { mlkemDecapsulate, mlkemEncapsulate } from '../mlkem.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

interface Vectors {
  argon2: {
    password: string;
    salt: string;
    time: number;
    memory: number;
    expected: string;
  };
  aes_gcm: {
    key: string;
    plaintext: string;
    ciphertext: string; // nonce prepended
  };
  x25519: {
    alice_priv: string;
    bob_pub: string;
    shared_secret: string;
  };
  hybrid_kem: {
    recipient_x25519_pub: string;
    recipient_mlkem_pub: string;
    recipient_x25519_priv: string;
    recipient_mlkem_priv: string;
    data_key: string;
    encrypted_key: string; // encrypted by Go, decrypted by TS
  };
  full_entry: {
    master_password: string;
    kdf_salt: string;
    kdf_time: number;
    kdf_memory: number;
    enc_priv_x25519: string;
    enc_priv_mlkem: string;
    pub_x25519: string;
    pub_mlkem: string;
    entry_encrypted_data: string; // encrypted by Go, decrypted by TS
    entry_encrypted_key: string;
    expected_username: string;
    expected_password: string;
  };
}

function b64Dec(s: string): Uint8Array {
  const binary = atob(s);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

describe('Go ↔ TypeScript interop', () => {
  let v: Vectors;

  beforeAll(async () => {
    const vectorPath = join(__dirname, '../../..', 'testdata', 'vectors.json');
    try {
      const raw = await readFile(vectorPath, 'utf-8');
      v = JSON.parse(raw) as Vectors;
    } catch {
      throw new Error(
        `Test vectors not found at ${vectorPath}.\n` +
          'Run: cd cli && go run ./cmd/gen-test-vectors -out ../packages/shared-ts/testdata/vectors.json',
      );
    }
  });

  it('Argon2id: TypeScript output matches Go output', async () => {
    const key = await deriveKey(v.argon2.password, {
      salt: b64Dec(v.argon2.salt),
      time: v.argon2.time,
      memory: v.argon2.memory,
    });
    expect(Buffer.from(key).toString('base64')).toBe(v.argon2.expected);
  }, 30_000);

  it('AES-GCM: TypeScript can decrypt Go ciphertext', async () => {
    const key = b64Dec(v.aes_gcm.key);
    const ciphertext = b64Dec(v.aes_gcm.ciphertext);
    const plaintext = await aesGcmDecrypt(key, ciphertext);
    expect(Buffer.from(plaintext).toString('base64')).toBe(v.aes_gcm.plaintext);
  });

  it('AES-GCM: Go can decrypt TypeScript ciphertext (via round-trip)', async () => {
    const key = b64Dec(v.aes_gcm.key);
    const plaintext = b64Dec(v.aes_gcm.plaintext);
    const ct = await aesGcmEncrypt(key, plaintext);
    const decrypted = await aesGcmDecrypt(key, ct);
    expect(decrypted).toEqual(plaintext);
  });

  it('X25519: TypeScript shared secret matches Go shared secret', () => {
    const alicePriv = b64Dec(v.x25519.alice_priv);
    const bobPub = b64Dec(v.x25519.bob_pub);
    const ss = x25519SharedSecret(alicePriv, bobPub);
    expect(Buffer.from(ss).toString('base64')).toBe(v.x25519.shared_secret);
  });

  it('Hybrid KEM: TypeScript can decrypt key encrypted by Go', async () => {
    const encKey = b64Dec(v.hybrid_kem.encrypted_key);
    const privX25519 = b64Dec(v.hybrid_kem.recipient_x25519_priv);
    const privMLKEM = b64Dec(v.hybrid_kem.recipient_mlkem_priv);
    const dataKey = await decryptDataKey(encKey, privX25519, privMLKEM);
    expect(Buffer.from(dataKey).toString('base64')).toBe(v.hybrid_kem.data_key);
  });

  it('Full entry: TypeScript can unlock and decrypt entry created by Go', async () => {
    const { aesGcmDecrypt } = await import('../aes-gcm.js');
    // Unlock: derive master key, decrypt private keys
    const masterKey = await deriveKey(v.full_entry.master_password, {
      salt: b64Dec(v.full_entry.kdf_salt),
      time: v.full_entry.kdf_time,
      memory: v.full_entry.kdf_memory,
    });
    const privX25519 = await aesGcmDecrypt(masterKey, b64Dec(v.full_entry.enc_priv_x25519));
    const privMLKEM = await aesGcmDecrypt(masterKey, b64Dec(v.full_entry.enc_priv_mlkem));

    // Decrypt entry
    const dataKey = await decryptDataKey(
      b64Dec(v.full_entry.entry_encrypted_key),
      privX25519,
      privMLKEM,
    );
    const plaintext = await aesGcmDecrypt(dataKey, b64Dec(v.full_entry.entry_encrypted_data));
    const data = JSON.parse(new TextDecoder().decode(plaintext));

    expect(data.username).toBe(v.full_entry.expected_username);
    expect(data.password).toBe(v.full_entry.expected_password);
  }, 30_000);
});
